# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6011a353737af66190bcabd86cd7319090352fbd44293dcbd7874bd8ae703c5d38ac359da48f8cf3c65c76afd9ab7c58f67d40e2c94da70190c9a3ca4b854af8

test:
  secret_key_base: 2c0b880ee5456ab148018971cad946d39bab32febf29dc02c4379ed100a407d576b7b65f9252a60add213a85d492bb7fc7af11bddb4b4154d57b1d9a94d79946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
